In [11]:
import pymongo
import pandas as pd

In [12]:
# Create connection variable
conn = 'mongodb://localhost:27017'
# Pass connection to the pymongo instance.
client = pymongo.MongoClient(conn)
# Connect to a database. Will create one if not already available.
db = client.jobs_db

In [13]:
jobs_data = list(db.jobs_glassdoor.find())
df = pd.DataFrame(jobs_data)
df = df.drop(['_id'], axis=1)
df.head()

,Avg Salary,City,Company,Designation,Max Salary,Min Salary,Source,State,Title
0,79.5,Baltimore,T. Rowe Price,Data Analyst,90.0,69.0,Glassdoor,MD,Data Analyst
1,79.5,Plano,Bank of America,Data Analyst,91.0,68.0,Glassdoor,TX,Data Analyst
2,59.5,Dallas,Freeman,Data Analyst,73.0,46.0,Glassdoor,TX,Analyst
3,62.5,Peachtree City,SMC 3,Data Analyst,72.0,53.0,Glassdoor,GA,Data Analyst
4,NaN,Asheville,"GPM, Corp",Data Analyst,NaN,NaN,Glassdoor,NC,Business Data Analyst

In [14]:
df = df.drop_duplicates(keep = 'first')
# df = df.loc[df["City"] != 'United States']

In [15]:
# grouped_df = df.groupby(['State', 'City'])
grp_company_df = df.groupby('Company')
# grouped_df.head()

In [16]:
# df['State'].value_counts()
# salary_df = grouped_df[["State", "City", "Avg Salary"]].mean()
# salary_df.head()

In [18]:
jobs_company_df = grp_company_df[["Company"]].count()
jobs_company_df = jobs_company_df.rename(columns = {"Company": "Jobs_Count"}).sort_values(by='Jobs_Count', ascending=False).reset_index()
jobs_company_df

                                  Company  Jobs Count
0                Phoenix Operations Group           4
1                       Walmart eCommerce           4
2                                PennyMac           3
3                 Smith Hanley Associates           2
4                      Fisher Investments           2
5                               GPM, Corp           2
6                              DTE Energy           2
7                                  Hopper           2
8                                    Uber           2
9    Loma Linda University Medical Center           2
10                               Vanguard           2
11            Seattle Children's Hospital           2
12                        Mutual of Omaha           2
13                                 Amazon           2
14                              Robinhood           1
15                            Radius Bank           1
16                          Organogenesis           1
17                   Reborn Cabinets Inc.           1
18                             ReliaQuest           1
19                      Optima Tax Relief           1
20                        Rent the Runway           1
21                              Percolate           1
22                     Puget Sound Energy           1
23                             S&P Global           1
24                            Oh My Green           1
25                                  SMC 3           1
26                Sammons Financial Group           1
27                              Sartorius           1
28                          Quicken Loans           1
29                        Protective Life           1
..                                    ...         ...
131                       Liberty Lending           1
132                                 MITRE           1
133                                  MUFG           1
134                          MarketSearch           1
135                      Marlette Funding           1
136                               Mastech           1
137                    Motive Interactive           1
138                N.F Smith & Associates           1
139                         ACI Worldwide           1
140                                   NPD           1
141          Investor Management Services           1
142                                 Intel           1
143                                  FCCI           1
144                      Healthline Media           1
145                             FM Global           1
146     Facing History and Ourselves, Inc           1
147                              Fanatics           1
148                       Fareportal Inc.           1
149                              Farfetch           1
150                       Fhlb Des Moines           1
151                   First Republic Bank           1
152                               Freeman           1
153              Frontier Technology, Inc           1
154                   GEI Consultants Inc           1
155                                   GSE           1
156                             Glassdoor           1
157                                  HAVI           1
158            HUNTER Technical Resources           1
159                    HealthEquity, Inc.           1
160                               ezCater           1

[161 rows x 2 columns]

In [19]:
# jobs_city_df = grouped_df[["City"]].count()
# jobs_city_df

In [ ]:
# picked_by_staff = kd_us_df.loc[kd_us_df["staff_pick"] == True]

In [20]:
json_company_jobs = jobs_company_df.to_json(orient='records')
json_company_jobs

'[{"Company":"Phoenix Operations Group","Jobs Count":4},{"Company":"Walmart eCommerce","Jobs Count":4},{"Company":"PennyMac","Jobs Count":3},{"Company":"Smith Hanley Associates","Jobs Count":2},{"Company":"Fisher Investments","Jobs Count":2},{"Company":"GPM, Corp","Jobs Count":2},{"Company":"DTE Energy","Jobs Count":2},{"Company":"Hopper","Jobs Count":2},{"Company":"Uber","Jobs Count":2},{"Company":"Loma Linda University Medical Center","Jobs Count":2},{"Company":"Vanguard","Jobs Count":2},{"Company":"Seattle Children\'s Hospital","Jobs Count":2},{"Company":"Mutual of Omaha","Jobs Count":2},{"Company":"Amazon","Jobs Count":2},{"Company":"Robinhood","Jobs Count":1},{"Company":"Radius Bank","Jobs Count":1},{"Company":"Organogenesis","Jobs Count":1},{"Company":"Reborn Cabinets Inc.","Jobs Count":1},{"Company":"ReliaQuest","Jobs Count":1},{"Company":"Optima Tax Relief","Jobs Count":1},{"Company":"Rent the Runway","Jobs Count":1},{"Company":"Percolate","Jobs Count":1},{"Company":"Puget Sound Energy","Jobs Count":1},{"Company":"S&P Global","Jobs Count":1},{"Company":"Oh My Green","Jobs Count":1},{"Company":"SMC 3","Jobs Count":1},{"Company":"Sammons Financial Group","Jobs Count":1},{"Company":"Sartorius","Jobs Count":1},{"Company":"Quicken Loans","Jobs Count":1},{"Company":"Protective Life","Jobs Count":1},{"Company":"Peterson Technology Partners","Jobs Count":1},{"Company":"PILLAR Inc.","Jobs Count":1},{"Company":"Professional Research Consultants","Jobs Count":1},{"Company":"Precima","Jobs Count":1},{"Company":"Powerley","Jobs Count":1},{"Company":"Point72","Jobs Count":1},{"Company":"Seventh Generation","Jobs Count":1},{"Company":"Planned Systems International","Jobs Count":1},{"Company":"Plaid","Jobs Count":1},{"Company":"Pitney Bowes","Jobs Count":1},{"Company":"Pinterest","Jobs Count":1},{"Company":"PROS","Jobs Count":1},{"Company":"Pactera","Jobs Count":1},{"Company":"Pluralsight","Jobs Count":1},{"Company":"8x8","Jobs Count":1},{"Company":"Siemens PLC","Jobs Count":1},{"Company":"Vivid Seats","Jobs Count":1},{"Company":"UC Davis Health","Jobs Count":1},{"Company":"United Airlines","Jobs Count":1},{"Company":"Urban Airship","Jobs Count":1},{"Company":"Valassis Digital","Jobs Count":1},{"Company":"VanderHouwen","Jobs Count":1},{"Company":"Verizon","Jobs Count":1},{"Company":"Vermont Information Processing","Jobs Count":1},{"Company":"Viwa","Jobs Count":1},{"Company":"Trividia Health","Jobs Count":1},{"Company":"Wells Fargo","Jobs Count":1},{"Company":"Welltower","Jobs Count":1},{"Company":"Westernacher","Jobs Count":1},{"Company":"WordStream","Jobs Count":1},{"Company":"Zimmerman Advertising","Jobs Count":1},{"Company":"Zynga","Jobs Count":1},{"Company":"comScore","Jobs Count":1},{"Company":"TrueAccord","Jobs Count":1},{"Company":"TripAdvisor","Jobs Count":1},{"Company":"Slack","Jobs Count":1},{"Company":"Systems & Technology Research","Jobs Count":1},{"Company":"Northwestern Mutual","Jobs Count":1},{"Company":"Spectrum Communications and Consulting","Jobs Count":1},{"Company":"Spok","Jobs Count":1},{"Company":"Spring Venture Group","Jobs Count":1},{"Company":"State Street Corporation","Jobs Count":1},{"Company":"Stripe","Jobs Count":1},{"Company":"Syndic8 Data Management Services, LLC","Jobs Count":1},{"Company":"T. Rowe Price","Jobs Count":1},{"Company":"Trillium Staffing","Jobs Count":1},{"Company":"Tableau Software","Jobs Count":1},{"Company":"Taco Bell","Jobs Count":1},{"Company":"Tapjoy","Jobs Count":1},{"Company":"Tax Defense Network","Jobs Count":1},{"Company":"TeraThink","Jobs Count":1},{"Company":"Torch Technologies","Jobs Count":1},{"Company":"Transfix","Jobs Count":1},{"Company":"Novetta","Jobs Count":1},{"Company":"NCSA - Next College Student Athlete","Jobs Count":1},{"Company":"Nokia","Jobs Count":1},{"Company":"CommerceHub","Jobs Count":1},{"Company":"CSAA Insurance Group","Jobs Count":1},{"Company":"CarGurus","Jobs Count":1},{"Company":"Caterpillar","Jobs Count":1},{"Company":"Central California Alliance for Health","Jobs Count":1},{"Company":"Chase","Jobs Count":1},{"Company":"Citadel Federal Credit Union","Jobs Count":1},{"Company":"Clarabridge","Jobs Count":1},{"Company":"Computershare","Jobs Count":1},{"Company":"NYC Data Science Academy","Jobs Count":1},{"Company":"Cummins","Jobs Count":1},{"Company":"Dimension Data","Jobs Count":1},{"Company":"EAB","Jobs Count":1},{"Company":"Eastman Kodak","Jobs Count":1},{"Company":"Education.com","Jobs Count":1},{"Company":"Elevate Credit","Jobs Count":1},{"Company":"Encore Fire Protection","Jobs Count":1},{"Company":"CME Group","Jobs Count":1},{"Company":"CGI Group, Inc.","Jobs Count":1},{"Company":"CACI International","Jobs Count":1},{"Company":"C2G Partners","Jobs Count":1},{"Company":"Advance Financial","Jobs Count":1},{"Company":"Affinity Health Plan","Jobs Count":1},{"Company":"Affinity Solutions","Jobs Count":1},{"Company":"Akamai","Jobs Count":1},{"Company":"AllianceBernstein","Jobs Count":1},{"Company":"American Bancshares Mortgage","Jobs Count":1},{"Company":"American Pacific Mortgage","Jobs Count":1},{"Company":"AmerisourceBergen","Jobs Count":1},{"Company":"Ancestry","Jobs Count":1},{"Company":"AnswerRocket","Jobs Count":1},{"Company":"Arcadia.io","Jobs Count":1},{"Company":"Attivio","Jobs Count":1},{"Company":"AutoNation","Jobs Count":1},{"Company":"Bank of America","Jobs Count":1},{"Company":"BioSoft Integrators","Jobs Count":1},{"Company":"Ericsson-Worldwide","Jobs Count":1},{"Company":"Everlane","Jobs Count":1},{"Company":"Everlaw","Jobs Count":1},{"Company":"Intent Media","Jobs Count":1},{"Company":"Jackson Lewis","Jobs Count":1},{"Company":"Kensho","Jobs Count":1},{"Company":"L.A. Care Health Plan","Jobs Count":1},{"Company":"LK Jordan","Jobs Count":1},{"Company":"LSQ","Jobs Count":1},{"Company":"Liberty Lending","Jobs Count":1},{"Company":"MITRE","Jobs Count":1},{"Company":"MUFG","Jobs Count":1},{"Company":"MarketSearch","Jobs Count":1},{"Company":"Marlette Funding","Jobs Count":1},{"Company":"Mastech","Jobs Count":1},{"Company":"Motive Interactive","Jobs Count":1},{"Company":"N.F Smith & Associates","Jobs Count":1},{"Company":"ACI Worldwide","Jobs Count":1},{"Company":"NPD","Jobs Count":1},{"Company":"Investor Management Services","Jobs Count":1},{"Company":"Intel","Jobs Count":1},{"Company":"FCCI","Jobs Count":1},{"Company":"Healthline Media","Jobs Count":1},{"Company":"FM Global","Jobs Count":1},{"Company":"Facing History and Ourselves, Inc","Jobs Count":1},{"Company":"Fanatics","Jobs Count":1},{"Company":"Fareportal Inc.","Jobs Count":1},{"Company":"Farfetch","Jobs Count":1},{"Company":"Fhlb Des Moines","Jobs Count":1},{"Company":"First Republic Bank","Jobs Count":1},{"Company":"Freeman","Jobs Count":1},{"Company":"Frontier Technology, Inc","Jobs Count":1},{"Company":"GEI Consultants Inc","Jobs Count":1},{"Company":"GSE","Jobs Count":1},{"Company":"Glassdoor","Jobs Count":1},{"Company":"HAVI","Jobs Count":1},{"Company":"HUNTER Technical Resources","Jobs Count":1},{"Company":"HealthEquity, Inc.","Jobs Count":1},{"Company":"ezCater","Jobs Count":1}]'