In [1]:
import pymongo
import pandas as pd
import json

In [2]:
# Create connection variable
conn = 'mongodb://localhost:27017'
# Pass connection to the pymongo instance.
client = pymongo.MongoClient(conn)
# Connect to a database. Will create one if not already available.
db = client.jobs_db

In [3]:
State = 'CA'

In [4]:
jobs_data = list(db.jobs_glassdoor.find())
df = pd.DataFrame(jobs_data)
df = df.drop(['_id'], axis=1)
df = df.drop_duplicates(keep = 'first')
# df = df.loc[df["Avg Salary"] > 0 ]
df = df.loc[df["State"] == State]
df

,Avg Salary,City,Company,Designation,Max Salary,Min Salary,Source,State,Title
6,65.0,Sacramento,UC Davis Health,Data Analyst,74.0,56.0,Glassdoor,CA,Research Data Analyst
11,107.0,Sunnyvale,Walmart eCommerce,Data Analyst,123.0,91.0,Glassdoor,CA,Data Analyst
13,117.0,Agoura Hills,PennyMac,Data Analyst,124.0,110.0,Glassdoor,CA,Data Engineer
15,NaN,Newark,Marlette Funding,Data Analyst,NaN,NaN,Glassdoor,CA,Marketing Data Analyst
17,110.0,San Francisco,Healthline Media,Data Analyst,127.0,93.0,Glassdoor,CA,Business Intelligence Data Analyst
18,58.0,Rocklin,American Pacific Mortgage,Data Analyst,66.0,50.0,Glassdoor,CA,Data Analyst
28,141.5,San Jose,Affinity Solutions,Data Analyst,160.0,123.0,Glassdoor,CA,Senior Big Data Analyst
30,117.0,Agoura Hills,PennyMac,Data Analyst,124.0,110.0,Glassdoor,CA,Data Engineer ETL
36,111.5,San Francisco,Zynga,Data Analyst,127.0,96.0,Glassdoor,CA,"Data Analyst 1-3, Words with Friends"
46,64.5,Loma Linda,Loma Linda University Medical Center,Data Analyst,79.0,50.0,Glassdoor,CA,GovernceRiskCompliance Analyst
51,78.5,San Francisco,Everlane,Data Analyst,91.0,66.0,Glassdoor,CA,Data Analyst
59,NaN,Burlingame,Oh My Green,Data Analyst,NaN,NaN,Glassdoor,CA,Senior Data Analyst
60,57.0,Irvine,Taco Bell,Data Analyst,69.0,45.0,Glassdoor,CA,Data Management Support Analyst
66,130.5,San Francisco,Pinterest,Data Analyst,161.0,100.0,Glassdoor,CA,"Product Analyst, Ads Quality"
71,67.0,San Jose,8x8,Data Analyst,79.0,55.0,Glassdoor,CA,Marketing Analyst
82,56.0,Santa Ana,Optima Tax Relief,Data Analyst,64.0,48.0,Glassdoor,CA,Client Data Analyst
84,90.5,Walnut Creek,CSAA Insurance Group,Data Analyst,113.0,68.0,Glassdoor,CA,Insurance Product Analyst
86,NaN,El Cajon,BioSoft Integrators,Data Analyst,NaN,NaN,Glassdoor,CA,"Analyst, Systems"
90,95.0,San Mateo,Education.com,Data Analyst,110.0,80.0,Glassdoor,CA,Business Intelligence Lead / Senior Data Analyst
94,83.5,San Francisco,First Republic Bank,Data Analyst,95.0,72.0,Glassdoor,CA,Data Analyst/Engineer
95,159.5,Menlo Park,Robinhood,Data Scientist,185.0,134.0,Glassdoor,CA,Data Scientist
96,115.5,Anaheim,Reborn Cabinets Inc.,Data Scientist,142.0,89.0,Glassdoor,CA,Data Scientist
106,180.5,Santa Clara,Akamai,Data Scientist,210.0,151.0,Glassdoor,CA,Senior Data Scientist
107,174.0,San Francisco,Stripe,Data Scientist,202.0,146.0,Glassdoor,CA,Data Scientist
111,NaN,Scotts Valley,Central California Alliance for Health,Data Scientist,NaN,NaN,Glassdoor,CA,Data Scientist III
112,NaN,San Francisco,Plaid,Data Scientist,NaN,NaN,Glassdoor,CA,Data Scientist
116,NaN,Oakland,Everlaw,Data Scientist,NaN,NaN,Glassdoor,CA,Data Scientist
119,156.5,San Francisco,TrueAccord,Data Scientist,182.0,131.0,Glassdoor,CA,Data Scientist
128,158.0,San Francisco,Slack,Data Scientist,184.0,132.0,Glassdoor,CA,"Data Scientist, Analytics"
132,143.5,San Mateo,Fanatics,Data Scientist,167.0,120.0,Glassdoor,CA,Data Scientist
141,124.0,Los Angeles,L.A. Care Health Plan,Data Scientist,146.0,102.0,Glassdoor,CA,Data Scientist
146,194.5,Sunnyvale,Walmart eCommerce,Data Scientist,225.0,164.0,Glassdoor,CA,Staff Data Scientist
147,194.5,Sunnyvale,Walmart eCommerce,Data Scientist,225.0,164.0,Glassdoor,CA,Staff Data Scientist - Machine Learning
157,117.0,Agoura Hills,PennyMac,Data Scientist,124.0,110.0,Glassdoor,CA,Data Engineer
164,160.0,Mill Valley,Glassdoor,Data Scientist,184.0,136.0,Glassdoor,CA,"Senior Data Scientist, Decision Science"
172,92.5,Loma Linda,Loma Linda University Medical Center,Data Scientist,108.0,77.0,Glassdoor,CA,Clinical Lab Scientist
173,213.0,San Bruno,Walmart eCommerce,Data Scientist,245.0,181.0,Glassdoor,CA,Principal Data Scientist
174,230.0,San Francisco,Tapjoy,Data Scientist,266.0,194.0,Glassdoor,CA,Staff Data Scientist
177,96.5,San Diego,Motive Interactive,Data Scientist,114.0,79.0,Glassdoor,CA,Data Scientist
180,164.0,Santa Clara,Ericsson-Worldwide,Data Scientist,191.0,137.0,Glassdoor,CA,Senior Machine Learning Engineer/Data Scientist

In [ ]:
grp_city_df = df.groupby('City')
    jobs_city_df = grp_city_df[["State"]].count()
    jobs_city_df = jobs_city_df.rename(
        columns = {"City": "Jobs_Count"}
        ).sort_values(by='Jobs_Count', ascending=False).reset_index()
    json_cities_jobs = jobs_city_df.to_json(orient='records')

In [26]:
json_data = []
items = ["State"] #, "City", "Company"]
for item in items:
    
    grp_df = df.groupby(item)
    sal_df = grp_df[['Avg Salary']].mean()
    job_df = grp_df[[item]].count().rename(columns = {item: "Jobs Count"})
    merged_table = pd.merge(sal_df, job_df, on= item)
    merged_table = merged_table.sort_values(by=['Jobs Count', 'Avg Salary'], ascending=False).head(20).reset_index()
    
    item_list = []
    sal_list = []
    count_list = []
    item_dict = {}
    for index, row in merged_table.iterrows() :
       # item_list.append(f"{row[item]}") 
       # sal_list.append(row['Avg Salary']) 
       # count_list.append(row['Jobs Count']) 
        item_dict = {"name": row[item],
                     "hours": row['Avg Salary']}
        json_data.append(item_dict)

In [27]:
# json_data = json_data.replace('"', "'") 
# json.dumps(json_data)

'[{"name": "CA", "hours": 124.20588235294117}, {"name": "NY", "hours": 110.78125}, {"name": "MA", "hours": 110.96666666666667}, {"name": "TX", "hours": 86.65}, {"name": "WA", "hours": 114.4375}, {"name": "VA", "hours": 94.35714285714286}, {"name": "FL", "hours": 75.21428571428571}, {"name": "IL", "hours": 98.25}, {"name": "MI", "hours": 123.5}, {"name": "PA", "hours": 128.33333333333334}, {"name": "GA", "hours": 109.16666666666667}, {"name": "NC", "hours": 101.16666666666667}, {"name": "MN", "hours": 102.75}, {"name": "VT", "hours": 91.25}, {"name": "CO", "hours": 75.0}, {"name": "OR", "hours": 70.5}, {"name": "RI", "hours": 147.0}, {"name": "IN", "hours": 135.0}, {"name": "CT", "hours": 111.5}, {"name": "NM", "hours": 106.0}]'